version: '3'
services:
  db:
    image: postgres
    ports:
      - 55432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  redis:
    image: redis
    ports:
      - 56379:6379