services:
  db:
    image: postgres:16-alpine
    ports:
      - 55432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 56379:6379
    volumes:
      - redis_data:/data

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: plunk
      MINIO_ROOT_PASSWORD: plunkminiopass
    volumes:
      - minio_data:/data

volumes:
  redis_data:
  minio_data:
  postgres_data: