services:
  db:
    image: postgres:16-alpine
    ports:
      - 55432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 56379:6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data:
